config/routes.rb
Rails.application.routes.draw do
  get 'pictures/:id' => 'pictures#show', as: 'picture'

  get 'jokes/:id' => 'jokes#show', as: 'joke'

  get 'articles/:id' => 'articles#show', as: 'article'

  get 'videos/:id' => 'videos#show', as: 'video'

  get 'comics/:id' => 'comics#show', as: 'comic'

  get 'about' => 'welcome#about'

  get 'archive/:date' => 'welcome#archive', as: 'front_page_archive'

  root 'welcome#home'

  get 'sitemap' => 'welcome#sitemap'

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :determine_source, only: [:show]

  def show
    @comic = @source.friendly.find(params[:id])
  end

  private

  def determine_source
    source = params[:source]
    @source = XkcdComic if source.eql?('xkcd.com')
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_comic_index_row.html.erb
<div class='col-md-1'>
  <div class='article-thumbnail'>
    <%= link_to comic_path(comic, source: comic.source) do %>
      <%= image_tag comic.thumbnail, class: 'img-responsive' %>
    <% end %>
  </div>
</div>
<div class='col-md-11'>
  <%= link_to comic.title, comic_path(comic, source: comic.source) %>
  <span class='inline-source'> (<%= link_to comic.source, comic.guid %>)</span>
</div>

app/views/comics/show.html.erb
<%
  meta title: "Comic - #{@comic.title}",
       keywords: @comic.content.remove_html_tags.to_keywords,
       og: { image: @comic.thumbnail }
%>

<div class="col-md-8">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @comic.title %></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <li class="list-group-item">
          <div class='img-responsive'>
            <%= @comic.content.html_safe %>
          </div>
          <br>
          <span class='inline-source'>(<%= link_to @comic.source, @comic.guid %>)</span>
        </li>
        <%= render 'layouts/share_this' %>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Our Sponsors</h3>
    </div>
    <div class="panel-body">
      <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- responsive-ad -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1535464165045682"
             data-ad-slot="1036549788"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </p>
    </div>
  </div>
</div>