config/routes.rb
Rails.application.routes.draw do
  get 'pictures/:id' => 'pictures#show', as: 'picture'

  get 'jokes/:id' => 'jokes#show', as: 'joke'

  get 'articles/:id' => 'articles#show', as: 'article'

  get 'videos/:id' => 'videos#show', as: 'video'

  get 'comics/:id' => 'comics#show', as: 'comic'

  get 'about' => 'welcome#about'

  get 'archive/:date' => 'welcome#archive', as: 'front_page_archive'

  root 'welcome#home'

  get 'sitemap' => 'welcome#sitemap'

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def show
    @video = BreakVideo.friendly.find(params[:id])
  end

end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/videos/_listing_panel_body.html.erb
<div class="panel-body">
  <ul class="list-group">
    <% @videos.each do |video| %>
      <li class="list-group-item slim-list-group-item">
        <div class='row'>

          <%= render 'video_index_row', video: video %>

        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/videos/_video_index_row.html.erb
<div class='col-md-1'>
  <div class='article-thumbnail'>
    <%= link_to video_path(video) do %>
      <% if video.thumbnail.is_probably_a_picture? %>
        <%= image_tag video.thumbnail, class: 'img-responsive' %>
      <% else %>
        <video autoplay loop muted preload width="80">
          <source src="<%= video.thumbnail %>" type='video/webm'>
          <source src="<%= video.thumbnail %>" type='video/mp4'>
        </video>
      <% end %>
    <% end %>
  </div>
</div>
<div class='col-md-11'>
  <%= link_to video.title, video_path(video) %>  <span class='inline-source'>
      (<%= link_to video.source, video.guid %>)</span>
</div>

app/views/videos/archive.html.erb
<%
  meta title: "Video Archive for #{params[:date]}",
       description: 'Top funny videos from the whole web',
       keywords: ['Funny Videos', 'Trending Videos', 'Funny Video Archive']
%>

<% if @videos.count > 0 %>
  <div id='outer-content-wrapper'>
    <%= will_paginate @videos, renderer: BootstrapPagination::Rails %>

    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Video Archive for <%= params[:date] %> from All Sources</h3>
      </div>
      <%= render 'listing_panel_body' %>
    </div>
  </div>
  <%= will_paginate @videos, renderer: BootstrapPagination::Rails %>
<% else %>
  <div id='inner-content-wrapper'>
    <%= image_tag 'derp.jpg' %>
  </div>
<% end %>

app/views/videos/index.html.erb
<%
  meta title: "Recent Videos",
       description: 'The most recent funny videos from the internet',
       keywords: ['Funny Videos', 'Trending Humor Videos', 'New Videos']
%>

<div id='outer-content-wrapper'>
  <%= will_paginate @videos, renderer: BootstrapPagination::Rails %><br>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">Recent Videos</h3>
    </div>
      <%= render 'listing_panel_body' %>
  </div>
  <%= will_paginate @videos, renderer: BootstrapPagination::Rails %>
</div>

app/views/videos/show.html.erb
<%
  meta title: @video.title,
       description: @video.summary.to_description,
       keywords: @video.title.to_keywords,
       og: { image: @video.thumbnail }
%>

<div class="col-md-8">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @video.title %></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <li class="list-group-item">
          <div class="embed-responsive embed-responsive-16by9">
            <video autoplay loop controls preload>
              <source src="<%= @video.video_link %>" type='video/webm'>
              <source src="<%= @video.video_link %>" type='video/mp4'>
            </video>
          </div>
          <br>
          Broken video? Try the source: <span class='inline-source'>(<%= link_to @video.source, @video.guid %>)</span>
        </li>
        <%= render 'layouts/share_this' %>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Our Sponsors</h3>
    </div>
    <div class="panel-body">
      <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- responsive-ad -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1535464165045682"
             data-ad-slot="1036549788"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </p>
    </div>
  </div>
</div>