config/routes.rb
Rails.application.routes.draw do
  get 'pictures/:id' => 'pictures#show', as: 'picture'

  get 'jokes/:id' => 'jokes#show', as: 'joke'

  get 'articles/:id' => 'articles#show', as: 'article'

  get 'videos/:id' => 'videos#show', as: 'video'

  get 'comics/:id' => 'comics#show', as: 'comic'

  get 'about' => 'welcome#about'

  get 'archive/:date' => 'welcome#archive', as: 'front_page_archive'

  root 'welcome#home'

  get 'sitemap' => 'welcome#sitemap'

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :determine_source, only: [:show]

  def show
    @picture = @source.friendly.find(params[:id])
  end

  private

  def determine_source
    if source = params[:source]
      @source = RedditFunnyPicture if source.eql?('reddit.com/r/funny')
      @source = MemesPicture if source.eql?('memes.com')
      @source = RedditAdviceAnimalsPicture if source.eql?('reddit.com/r/adviceanimals')
    else
      guess_at_the_source
    end
  end

  def guess_at_the_source
    if RedditFunnyPicture.where(slug: params[:id]).present?
      @source = RedditFunnyPicture
    elsif RedditAdviceAnimalsPicture.where(slug: params[:id]).present?
      @source = RedditAdviceAnimalsPicture
    else
      @source = MemesPicture
    end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def gifv_sub_webm(str)
    str.ends_with?('.gifv') ? str.gsub('.gifv', '.webm') : str
  end

  def gifv_sub_mp4(str)
    str.ends_with?('.gifv') ? str.gsub('.gifv', '.mp4') : str
  end

  def no_direct_link?(img)
    imgur_gallery?(img) || live_meme?(img) || img_flip?(img)
  end

  def imgur_gallery?(str)
    str.match(/imgur.com\/gallery/) || str.match(/imgur.com\/a\//)
  end

  def live_meme?(str)
    str.match(/livememe.com/)
  end

  def img_flip?(str)
    str.match(/imgflip.com/)
  end
end

app/views/pictures/_listing_panel_body.html.erb
<div class="panel-body">
  <ul class="list-group">
    <% @pictures.each do |picture| %>
      <li class="list-group-item slim-list-group-item">
        <div class='row'>

          <%= render 'picture_index_row', picture: picture %>

        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/pictures/_picture_index_row.html.erb
<div class='col-md-1'>
  <div class='article-thumbnail'>
    <% if no_direct_link?(picture.actual_image) %>
      <%= link_to picture.actual_image do %>
        <%= image_tag picture.thumbnail, class: 'img-responsive' %>
      <% end %>
    <% else %>
      <%= link_to picture_path(picture, source: picture.source) do %>
        <%= image_tag picture.thumbnail, class: 'img-responsive' %>
      <% end %>
    <% end %>
  </div>
</div>
<div class='col-md-11'>
  <% if no_direct_link?(picture.actual_image) %>
    <%= link_to picture.title, picture.actual_image %>
  <% else %>
    <%= link_to picture.title, picture_path(picture, source: picture.source) %>
  <% end %>
  <span class='inline-source'> (<%= link_to picture.source, picture.guid %>)</span>
</div>

app/views/pictures/archive.html.erb
<%
  meta title: "Picture Archive for #{params[:date]}",
       description: 'Top Images, gifs, jpgs, memes, etc from the web',
       keywords: ['Funny Pictures', 'Funny Gifs', 'New Funny Images']
%>

<% if @pictures.count > 0 %>
  <div id='outer-content-wrapper'>
    <%= will_paginate @pictures, renderer: BootstrapPagination::Rails %>

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Picture Archive for <%= params[:date] %> from All Sources</h3>
      </div>
      <%= render 'listing_panel_body' %>
    </div>
  </div>
  <%= will_paginate @pictures, renderer: BootstrapPagination::Rails %>
<% else %>
  <div id='inner-content-wrapper'>
    <%= image_tag 'derp.jpg' %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<%
  meta title: "Recent Pictures",
       description: 'The most recent funny pictures from the internet',
       keywords: ['Funny Pictures', 'Funny Gifs', 'New Funny Images']
%>

<div id='outer-content-wrapper'>
  <%= will_paginate @pictures, renderer: BootstrapPagination::Rails %><br>
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">Recent Pictures</h3>
    </div>
      <%= render 'listing_panel_body' %>
  </div>
  <%= will_paginate @pictures, renderer: BootstrapPagination::Rails %>
</div>

app/views/pictures/show.html.erb
<%
  meta title: @picture.title,
       keywords: @picture.title.to_keywords,
       og: { image: @picture.thumbnail }
%>

<div class="col-md-8">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @picture.title %></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <li class="list-group-item">
          <% if @picture.actual_image.ends_with?('.gifv') %>
            <video autoplay loop muted preload>
              <source src="<%= gifv_sub_webm(@picture.actual_image) %>" type='video/webm'>
              <source src="<%= gifv_sub_mp4(@picture.actual_image) %>" type='video/mp4'>
            </video>
          <% else %>
            <%= image_tag @picture.actual_image, class: 'img-responsive' %>
          <% end %>
          <br>
          <span class='inline-source'>(<%= link_to @picture.source, @picture.guid %>)</span>
        </li>
        <%= render 'layouts/share_this' %>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Our Sponsors</h3>
    </div>
    <div class="panel-body">
      <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- responsive-ad -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1535464165045682"
             data-ad-slot="1036549788"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </p>
    </div>
  </div>
</div>