config/routes.rb
Rails.application.routes.draw do
  get 'pictures/:id' => 'pictures#show', as: 'picture'

  get 'jokes/:id' => 'jokes#show', as: 'joke'

  get 'articles/:id' => 'articles#show', as: 'article'

  get 'videos/:id' => 'videos#show', as: 'video'

  get 'comics/:id' => 'comics#show', as: 'comic'

  get 'about' => 'welcome#about'

  get 'archive/:date' => 'welcome#archive', as: 'front_page_archive'

  root 'welcome#home'

  get 'sitemap' => 'welcome#sitemap'

end

app/views/layouts/_date_picker.html.erb
<form method='link' action='#' id='archive-date-form' class="form-inline <%= css %>" data-root-url="/archive<%= channel %>/">
  <div class="form-group">
    <input type="text" class="form-control" id="datepicker" placeholder="Select Date">
  </div>
</form>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="\">Internet Vortex [alpha]</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Archive", front_page_archive_path(DateTime.now.yesterday.strftime('%B-%d-%Y')) %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= mail_to 'internetvortex2015@gmail.com', 'Contact' %></li>
        <% if @archive %>
          <li>
            <%= render 'layouts/date_picker', { channel: @channel, css: "" } %>
          </li>
        <% end %>
        <li class="nav-share"><span class='st_sharethis_large' displayText='ShareThis'></span></li>
        <li class="nav-share">
          <!-- Place this tag where you want the su badge to render -->
          <su:badge layout="6"></su:badge>

          <!-- Place this snippet wherever appropriate -->
          <script type="text/javascript">
          (function() {
          var li = document.createElement('script'); li.type = 'text/javascript'; li.async = true;
          li.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + '//platform.stumbleupon.com/1/widgets.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(li, s);
          })();
          </script>
        </li>
      </ul>
      <% if false %>
        <!-- no facebook until launch -->
        <div id='social-container'>
          <div class="fb-like" data-share="true" data-width="450" data-show-faces="true"></div>
        </div>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<% if flash.present? %>
  <div id="navbar-spacer"></div>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<% end %>

app/views/layouts/_recent_links.html.erb
<div class="col-md-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Archive Quick Links</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <% @recent_days.each do |day| %>
          <li class="list-group-item slim-list-group-item">
            <%= link_to day, front_page_archive_path(date: day) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Our Sponsors</h3>
    </div>
    <div class="panel-body">
      <p>
        <div id="b5c967fbae" class="pagefair-acceptable"></div>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- responsive-ad -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1535464165045682"
             data-ad-slot="1036549788"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_right_ad_column.html.erb
<% 6.times do %>
  <%= render 'layouts/three_ad_block' %>
<% end %>

app/views/layouts/_share_this.html.erb
<li class="list-group-item">
  <span class='st_sharethis_large' displayText='ShareThis'></span>
  <span class='st_facebook_large' displayText='Facebook'></span>
  <span class='st_twitter_large' displayText='Tweet'></span>
  <span class='st_stumbleupon_large' displayText='StumbleUpon'></span>
  <span class='st_pinterest_large' displayText='Pinterest'></span>
  <span class='st_linkedin_large' displayText='LinkedIn'></span>
  <span class='st_email_large' displayText='Email'></span>
</li>

app/views/layouts/_three_ad_block.html.erb
<p>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- responsive-ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-1535464165045682"
       data-ad-slot="1036549788"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</p>

<p>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- responsive-display-1 -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-1535464165045682"
       data-ad-slot="9419270982"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</p>

<p>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- responsive-text-ad-minimal -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-1535464165045682"
       data-ad-slot="1896004186"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%
      metamagic site: "InternetVortex: Funny", title: [:title, :site], separator: " — "
    %>

    <%
      meta og: { image: "https://cdn2.iconfinder.com/data/icons/freecns-cumulus/32/519909-102_Tornado-128.png" }
    %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= metamagic %>

    <!-- Sharethis -->
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "33c7f351-79e9-477e-bcf3-ce71da003803", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

    <!-- Pagefair -->
    <script type="text/javascript">
        (function() {
            function async_load(script_url){
                var protocol = ('https:' == document.location.protocol ? 'https://' : 'http://');
                var s = document.createElement('script'); s.src = protocol + script_url;
                var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
            }
            bm_website_code = '6CF72B656F3F4CE2';
            jQuery(document).ready(function(){async_load('asset.pagefair.com/measure.min.js')});
            jQuery(document).ready(function(){async_load('asset.pagefair.net/ads.min.js')});
        })();
    </script>

    <!-- Google Analytics -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <% if Rails.env.production? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-60633640-1', 'auto');
        ga('send', 'pageview');

      </script>
    <% end %>
  </head>
  <body>
    <% if false %>
       <!-- Just turning off FB until launch -->
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '1554449104836544',
            xfbml      : true,
            version    : 'v2.2'
          });
        };

        (function(d, s, id){
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement(s); js.id = id;
           js.src = "//connect.facebook.net/en_US/sdk.js";
           fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));
      </script>
    <% end %>

    <%= render 'layouts/navbar' %>
    <div class='container-fluid'>
      <div id='outer-content-wrapper'>
        <div class="row">

          <%= yield %>

        </div>
        <div class='row'>
          <div id="ebbcb648d3" class="pagefair-acceptable"></div>
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <!-- footer-banner -->
          <ins class="adsbygoogle"
               style="display:inline-block;width:728px;height:90px"
               data-ad-client="ca-pub-1535464165045682"
               data-ad-slot="4849470586"></ins>
          <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
        </div>
      </div>
    </div>
  </body>
</html>